version: '2'

checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
  # There is an eslint rule for that which allows for finer control, e.g.
  # Ignoring this rule for hooks because they can get long pretty easily.
  method-lines:
    enabled: false

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          count_threshold: 3
        javascript:
          count_threshold: 3

exclude_patterns:
  - '**/__tests__/**/*'
  - 'src/graphql/generated.ts'
  - 'src/graphql/generated/**/*.ts'
