version: '2'

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          count_threshold: 3
        javascript:
          count_threshold: 3

exclude_patterns:
  - '**/__tests__/**/*'
  - 'src/graphql/generated.ts'
  - 'src/graphql/generated/**/*.ts'
